version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo install step...  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=622169599480.dkr.ecr.ap-northeast-1.amazonaws.com/portfolio_app-image-repo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t portfolio_app-image-repo:latest .
      - docker tag portfolio_app-image-repo:latest 622169599480.dkr.ecr.ap-northeast-1.amazonaws.com/$portfolio_app-image-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push 622169599480.dkr.ecr.ap-northeast-1.amazonaws.com/portfolio_app-image-repo:latest
  artifacts:
    files: 
      - imagedefinitions.json