version: '3'
services:
  app:
    build: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/portfolio_app
      - ./public/data:/portfolio_app/public
      - ./tmp/data:/portfolio_app/tmp
      - ./log/data:/portfolio_app/log
    ports:
      - "3000:3000" 
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - ./db/data:/var/lib/mysql
    ports: 
      - "3306:3306"

  web:
    build:
      context: containers/nginx
    volumes:
      - ./public/data:/portfolio_app/public
      - ./tmp/data:/portfolio_app/tmp
    ports:
      - "8080:8080"
    depends_on:
      - app